
/*
ORCAMENTO
258209
23013

OS
142606
23013
*/

SELECT * FROM ITM_OS WHERE COD_OS IN( 142606)
SELECT * FROM OS_NF  WHERE COD_OS =142606
SELECT * FROM ITM_NFE_SAIDA where COD_NF_SAIDA =17238 

SELECT * FROM ORCAMENTOS WHERE COD_ORCA IN( 258209,237386)


SELECT ORCA.COD_ORCA AS CODIGO, ORCA.COD_CLI AS CODIGOCLIENTE, CLI.NOME_CLI AS NOMECLIENTE,  
FUNC.NOME_FUNC AS NOMEFUCNIONARIO,UPPER(E.DESC_ENT) ENTRGA  ,CLI.EST_CLI AS ESTADO ,
CASE ORCA.EMPRESA_ORCA 
WHEN 'T' THEN 'TECHCD' 
WHEN 'M' THEN 'MIDIA' 
WHEN 'D' THEN 'DATA' 
END AS EMPRESA ,
ORCA.DATA_ORCA , ORCA.TOT_ORCA , ORCA.SUBST_TRIBUTARIA , ORCA.FRETE_ORCA  ,
I.COD_PROD , P.DESC_PROD ,I.QTDE_ORCA , I.VALOR_ORCA ,P.CLASSITRIB_PROD 
FROM ORCAMENTOS AS ORCA
INNER JOIN CLIENTES AS CLI ON CLI.COD_CLI = ORCA.COD_CLI
INNER JOIN FUNCIONARIOS AS FUNC ON FUNC.COD_FUNC = ORCA.COD_VEND
INNER JOIN ITM_ORCA AS I ON I.COD_ORCA = ORCA.COD_ORCA 
INNER JOIN PRODUTOS AS P ON P.COD_PROD =  I.COD_PROD
INNER JOIN ENTREGAS AS E ON E.COD_ENT =  ORCA.COD_ENT
WHERE ORCA.COD_ORCA IN( 258209,237386) AND I.COD_PROD = 23013


