
SELECT I.COD_OS , I.VAL_PAGTO , I.REAL_PAGTO , I.QUEMQUIT_OS , I.DATAQUIT_OS , I.DATAQUIT_OS,
T.DESC_PAGTO, F.DESC_FRMPAGTO
FROM  
ITM_OS_PAGTO AS I, TIPO_PAGTO AS T , FORMA_PAGTO AS F
WHERE 
I.COD_PAGTO = T.COD_PAGTO AND
I.COD2_FRMPAGTO = F.COD_FRMPAGTO AND
I.COD_OS = 155936