

SELECT ITEM.COD_ORCA AS CODIGOORCAMENTO , 
ITEM.COD_PROD AS CODIGOPRODUTO , PROD.DESC_PROD ,  
PROD.CLASSITRIB_PROD AS CLASSIFICASAOFISCA ,
ITEM.QTDE_ORCA AS QUANTIDADE , 
ITEM.VALOR_ORCA AS VALOR ,
ITEM.QTDE_ORCA *ITEM.VALOR_ORCA as VALORTOTAL
FROM ITM_ORCA AS ITEM 
INNER  JOIN PRODUTOS AS PROD ON PROD.COD_PROD = ITEM.COD_PROD
WHERE ITEM.COD_ORCA = 256075


