DECLARE @STARTER AS DATETIME = '2016-07-01';
DECLARE @FINISH  AS DATETIME = '2016-07-30';
SELECT cod_prod AS [CODIGO] , cod_ref AS [REFERENCIA], MOVIMENTACAO_TECHCD.QTDE_MOV, 
CASE STATUS_MOV  
WHEN 'S' THEN 'SAIDA' 
WHEN 'E' THEN 'ENTRADA'
WHEN 'A' THEN 'AJUSTE'
WHEN 'C' THEN 'CANCELADO'
WHEN 'T' THEN 'TROCA' 
WHEN 'M' THEN 'AMOSTRA'
WHEN 'R' THEN 'REJEITADO' 
WHEN 'I' THEN 'USO INTERNO'
WHEN 'K' THEN 'SILK' 
WHEN 'D' THEN 'DEVOLU플O'
WHEN 'W' THEN 'TRANS MIDIA'
WHEN 'X' THEN 'TRANS DATA' 
WHEN 'Z' THEN 'TRANS TECHCD'
WHEN 'Y' THEN 'TRANSFERENCIA'
END AS [STATUS] , 
CONVERT(NVARCHAR, DATA_MOV, 103)  as [MOVIMENTA플O] , 'TECHCD'AS [EMPRESA] from MOVIMENTACAO_TECHCD
WHERE DATA_MOV BETWEEN  @STARTER AND @FINISH

UNION 
SELECT cod_prod AS [CODIGO] , cod_ref AS [REFERENCIA],  MOVIMENTACAO_DATASTORE.QTDE_MOV, 
CASE STATUS_MOV  
WHEN 'S' THEN 'SAIDA' 
WHEN 'E' THEN 'ENTRADA'
WHEN 'A' THEN 'AJUSTE'
WHEN 'C' THEN 'CANCELADO'
WHEN 'T' THEN 'TROCA' 
WHEN 'M' THEN 'AMOSTRA'
WHEN 'R' THEN 'REJEITADO' 
WHEN 'I' THEN 'USO INTERNO'
WHEN 'K' THEN 'SILK' 
WHEN 'D' THEN 'DEVOLU플O'
WHEN 'W' THEN 'TRANS MIDIA'
WHEN 'X' THEN 'TRANS DATA' 
WHEN 'Z' THEN 'TRANS TECHCD'
WHEN 'Y' THEN 'TRANSFERENCIA'
END AS [STATUS] , 
CONVERT(NVARCHAR, DATA_MOV, 103)  as [MOVIMENTA플O] , 'DATA STORE'AS [EMPRESA] from MOVIMENTACAO_DATASTORE
WHERE DATA_MOV BETWEEN  @STARTER AND @FINISH

UNION 
SELECT cod_prod AS [CODIGO] , cod_ref AS [REFERENCIA], MOVIMENTACAO_MIDIACENTER.QTDE_MOV, 
CASE STATUS_MOV  
WHEN 'S' THEN 'SAIDA' 
WHEN 'E' THEN 'ENTRADA'
WHEN 'A' THEN 'AJUSTE'
WHEN 'C' THEN 'CANCELADO'
WHEN 'T' THEN 'TROCA' 
WHEN 'M' THEN 'AMOSTRA'
WHEN 'R' THEN 'REJEITADO' 
WHEN 'I' THEN 'USO INTERNO'
WHEN 'K' THEN 'SILK' 
WHEN 'D' THEN 'DEVOLU플O'
WHEN 'W' THEN 'TRANS MIDIA'
WHEN 'X' THEN 'TRANS DATA' 
WHEN 'Z' THEN 'TRANS TECHCD'
WHEN 'Y' THEN 'TRANSFERENCIA'
END AS [STATUS] , 
CONVERT(NVARCHAR, DATA_MOV, 103)  as [MOVIMENTA플O] , 'MIDIA CENTER'AS [EMPRESA] from MOVIMENTACAO_MIDIACENTER
WHERE DATA_MOV BETWEEN  @STARTER AND @FINISH


