

SELECT m.COD_PROD AS CODIGO, M.SALDOMIDIA_MOV AS [SALDO MIDIA],
CONVERT(NVARCHAR,R.MaxTime,103) AS [ULTIMA MOVIMENTACAO] , 
UPPER(P.DESC_PROD) AS [DESCRIÇÃO PRODUTO] , p.CLASSITRIB_PROD as NCM , 
 min(pc.IMP_PRE) as [VALOR UNIT] , m.SALDOMIDIA_MOV * min(pc.IMP_PRE) as [VALOR TOTAL]
FROM (SELECT cod_prod, MAX(DATA_MOV) as MaxTime
      FROM MOVIMENTACAO_MIDIACENTER where DATA_MOV < '2015-01-28'
      GROUP BY COD_PROD) r
INNER JOIN MOVIMENTACAO_MIDIACENTER m ON m.COD_PROD = r.COD_PROD AND m.DATA_MOV = r.MaxTime
inner join PRODUTOS as p on p.COD_PROD = m.COD_PROD 
inner join PRODUTOS_QTDE as pq on pq.COD_PROD = m.COD_PROD 
inner join PRECOS_PROD as pc on pc.COD_PROD =  m.COD_PROD
where m.SALDOMIDIA_MOV > 0  and m.COD_PROD >  10008 
and p.COD_CAT <> 29 and p.COD_CAT <> 57
group by m.COD_PROD, r.MaxTime , p.DESC_PROD  ,M.SALDOMIDIA_MOV , p.CLASSITRIB_PROD
order by m.COD_PROD asc 
