
DECLARE @TAB TABLE (ARQ NVARCHAR(255))
INSERT INTO @TAB EXEC  master..xp_cmdshell 'dir \\file_server\fotos\*.gif /b' 
SELECT p.COD_PROD , p.DESC_PROD , CAT.DESC_CAT , 
pq.QTDE_TECH , pq.QTDE_DATA ,  pq.QTDE_MIDIA 
FROM PRODUTOS AS P
INNER JOIN PRODUTOS_QTDE AS PQ ON PQ.COD_PROD =  P.COD_PROD
INNER JOIN CATEGORIAS AS CAT ON CAT.COD_CAT =  P.COD_CAT
WHERE p.COD_CAT <> 29 and p.COD_CAT <> 57  
AND NOT EXISTS 
(SELECT 1 FROM @TAB WHERE rtrim(ARQ) = RTRIM(CONVERT(CHAR,P.COD_PROD))+'.gif')
AND NOT EXISTS
(SELECT 1 FROM @TAB WHERE rtrim(ARQ) = RTRIM(CONVERT(CHAR,P.COD_PROD))+'p.gif')

