SELECT PROD.COD_PROD AS CODIGO, PROD.DESC_PROD AS DESCRICAO ,CAT.DESC_CAT AS CATEGORIA,
PROD.SALDO_PROD AS SALDOPROD, PROD.TEORICO_PROD AS SALDOTEORICOPROD,
QTD.QTDE_DATA AS QTDEDATA, QTD.TEORICO_DATA AS TEORICODATA, QTD.QTDE_MIDIA AS QTDEMIDIA , 
QTD.TEORICO_MIDIA AS TEORICOMIDIA,QTD.QTDE_TECH AS QDTETECH, QTD.TEORICO_TECH AS TEOCRICOTECH
FROM PRODUTOS AS PROD
INNER JOIN CATEGORIAS AS CAT ON CAT.COD_CAT =  PROD.COD_CAT
INNER JOIN PRODUTOS_QTDE AS QTD ON QTD.COD_PROD = PROD.COD_PROD
ORDER BY PROD.COD_PROD ASC 