USE techcd

--drop table #TEMP_ESTOQUE_DATA

CREATE TABLE #TEMP_ESTOQUE_DATA
(ID INT NOT NULL IDENTITY(1,1), 
DATA DATE NOT NULL  )

INSERT INTO #TEMP_ESTOQUE_DATA VALUES ('2016-07-30')




DECLARE @ID AS  INT
DECLARE  @periodo as datetime 
WHILE( EXISTS (SELECT 1 FROM #TEMP_ESTOQUE_DATA))
BEGIN   
	SELECT TOP 1 @periodo =  DATA FROM #TEMP_ESTOQUE_DATA ORDER BY ID
--TECHCD 
SELECT convert(nvarchar,@periodo,103) as PERIODO, 
'TECHCD' AS EMPRESA ,
m.COD_PROD AS CODIGO,
UPPER(P.DESC_PROD) AS [DESCRIÇÃO PRODUTO] ,
cat.COD_CAT  AS [COD CATEGORIA], 
cat.DESC_CAT AS [DESC CATEGORIA], 
g.COD_GRUPO AS [COD GRUPO],
g.DESC_GRUPO AS [DESC GRUPO],
convert(nvarchar,r.MaxTime,103) AS [ULTIMA MOVIMENTACAO],
M.SALDOTECH_MOV AS [SALDO TECH],
p.CUSTO_PROD AS [CUSTO PROD],
p.CUSTOREF_PROD AS [CUSTO REFERENCIA],
p.MED_PROD AS [MEDIA PROD],
max(pc.IMP_PRE) as [VALOR UNIT] 
FROM (SELECT cod_prod, MAX(DATA_MOV) as MaxTime
      FROM MOVIMENTACAO_TECHCD where DATA_MOV < @periodo
      GROUP BY COD_PROD) r
INNER JOIN MOVIMENTACAO_TECHCD m ON m.COD_PROD = r.COD_PROD AND m.DATA_MOV = r.MaxTime
inner join PRODUTOS as p on p.COD_PROD = m.COD_PROD 
inner join PRODUTOS_QTDE as pq on pq.COD_PROD = m.COD_PROD 
inner join PRECOS_PROD as pc on pc.COD_PROD =  m.COD_PROD
inner join CATEGORIAS AS cat on cat.COD_CAT = p.COD_CAT
inner join GRUPO_PRODUTOS as g on g.COD_GRUPO =  p.COD_GRUPO
where m.SALDOTECH_MOV > 0  and m.COD_PROD >  10008 
and p.COD_CAT <> 29 and p.COD_CAT <> 57
group by m.COD_PROD, r.MaxTime , p.DESC_PROD  ,M.SALDOTECH_MOV , p.CLASSITRIB_PROD, 
p.COD_CAT, cat.DESC_CAT, cat.COD_SUPERCAT, g.COD_GRUPO, g.DESC_GRUPO ,  p.CUSTO_PROD,
p.CUSTOREF_PROD, p.MED_PROD , cat.COD_CAT

UNION ALL 

-- MIDIA
SELECT convert(nvarchar,@periodo,103) as PERIODO, 
'MIDIA' AS EMPRESA ,
m.COD_PROD AS CODIGO,
UPPER(P.DESC_PROD) AS [DESCRIÇÃO PRODUTO] ,
cat.COD_CAT  AS [COD CATEGORIA], 
cat.DESC_CAT AS [DESC CATEGORIA], 
g.COD_GRUPO AS [COD GRUPO],
g.DESC_GRUPO AS [DESC GRUPO],
convert(nvarchar,r.MaxTime,103) AS [ULTIMA MOVIMENTACAO],
M.SALDOMIDIA_MOV AS [SALDO TECH],
p.CUSTO_PROD AS [CUSTO PROD],
p.CUSTOREF_PROD AS [CUSTO REFERENCIA],
p.MED_PROD AS [MEDIA PROD],
max(pc.IMP_PRE) as [VALOR UNIT] 
FROM (SELECT cod_prod, MAX(DATA_MOV) as MaxTime
      FROM MOVIMENTACAO_MIDIACENTER where DATA_MOV < @periodo
      GROUP BY COD_PROD) r
INNER JOIN MOVIMENTACAO_MIDIACENTER m ON m.COD_PROD = r.COD_PROD AND m.DATA_MOV = r.MaxTime
inner join PRODUTOS as p on p.COD_PROD = m.COD_PROD 
inner join PRODUTOS_QTDE as pq on pq.COD_PROD = m.COD_PROD 
inner join PRECOS_PROD as pc on pc.COD_PROD =  m.COD_PROD
inner join CATEGORIAS AS cat on cat.COD_CAT = p.COD_CAT
inner join GRUPO_PRODUTOS as g on g.COD_GRUPO = p.COD_GRUPO
where m.SALDOMIDIA_MOV > 0  and m.COD_PROD >  10008 
and p.COD_CAT <> 29 and p.COD_CAT <> 57
group by m.COD_PROD, r.MaxTime , p.DESC_PROD  ,M.SALDOMIDIA_MOV , p.CLASSITRIB_PROD, 
p.COD_CAT, cat.DESC_CAT, cat.COD_SUPERCAT, g.COD_GRUPO, g.DESC_GRUPO ,  p.CUSTO_PROD,
p.CUSTOREF_PROD, p.MED_PROD , cat.COD_CAT

UNION ALL 

--DATA
SELECT convert(nvarchar,@periodo,103) as PERIODO, 
'DATA' AS EMPRESA ,
m.COD_PROD AS CODIGO,
UPPER(P.DESC_PROD) AS [DESCRIÇÃO PRODUTO] ,
cat.COD_CAT  AS [COD CATEGORIA], 
cat.DESC_CAT AS [DESC CATEGORIA], 
g.COD_GRUPO AS [COD GRUPO],
g.DESC_GRUPO AS [DESC GRUPO],
convert(nvarchar,r.MaxTime,103) AS [ULTIMA MOVIMENTACAO],
M.SALDODATA_MOV AS [SALDO TECH],
p.CUSTO_PROD AS [CUSTO PROD],
p.CUSTOREF_PROD AS [CUSTO REFERENCIA],
p.MED_PROD AS [MEDIA PROD],
max(pc.IMP_PRE) as [VALOR UNIT] 
FROM (SELECT cod_prod, MAX(DATA_MOV) as MaxTime
      FROM MOVIMENTACAO_DATASTORE where DATA_MOV < @periodo
      GROUP BY COD_PROD) r
INNER JOIN MOVIMENTACAO_DATASTORE m ON m.COD_PROD = r.COD_PROD AND m.DATA_MOV = r.MaxTime
inner join PRODUTOS as p on p.COD_PROD = m.COD_PROD 
inner join PRODUTOS_QTDE as pq on pq.COD_PROD = m.COD_PROD 
inner join PRECOS_PROD as pc on pc.COD_PROD =  m.COD_PROD
inner join CATEGORIAS AS cat on cat.COD_CAT = p.COD_CAT
inner join GRUPO_PRODUTOS as g on g.COD_GRUPO = p.COD_GRUPO
where m.SALDODATA_MOV > 0  and m.COD_PROD >  10008 
and p.COD_CAT <> 29 and p.COD_CAT <> 57
group by m.COD_PROD, r.MaxTime , p.DESC_PROD  ,M.SALDODATA_MOV , p.CLASSITRIB_PROD, 
p.COD_CAT, cat.DESC_CAT, cat.COD_SUPERCAT, g.COD_GRUPO, g.DESC_GRUPO ,  p.CUSTO_PROD,
p.CUSTOREF_PROD, p.MED_PROD , cat.COD_CAT

	DELETE #TEMP_ESTOQUE_DATA WHERE DATA = @periodo
END  


