/*
select * from CONTRATO_CLIENTE 
select * from CLIENTES_CONTRATO
SELECT * FROM CONTRATO
*/

DECLARE @INI AS DATETIME =  '2016-01-01'
DECLARE @FIM AS DATETIME =  '2016-31-07'



SELECT 'TECHCD' AS ENPRESA,  NFE.COD_NF_SAIDA AS CODIGO, CONVERT(NVARCHAR,NFE.DATAEMIS_NF_SAIDA,103) AS DATA_EMISSAO_NFE,  
OS_NF.COD_OS AS OS, CONVERT(NVARCHAR,OS.DATA2_OS,103) AS DATA_EMISSAO_OS, CLI.COD_CLI AS CODIGO_CLIENTE,
CLI.NOME_CLI AS NOME_CLIENTE, CASE 
WHEN CLI.PES_CLI = 'j' THEN CLI.CNPJ_CLI
ELSE CLI.CPF_CLI END CNPJ_CPF, NAT.DESC_NAT AS [NATUREZA DA OPERAÇÃO] ,CONTRATO.NUM_CONTRATO CODIGO_CONTRATO, 
NFE.TOTFRETE_NF_SAIDA AS VALOR_FRETE, NFE.TOTPROD_NF_SAIDA AS TOTAL_PRODUTO, NFE.TOTSERV_NF_SAIDA AS TOTAL_SERVICO, 
NFE.SUBST_TRIBUTARIA AS ST,NFE.VAL_ICMS AS ICMS, 
NFE.IPI_NF_SAIDA AS IPI, NFE.TOTAL_NF_SAIDA AS TOTAL_NFE , 
CASE 
WHEN NFE.CANC_NF_SAIDA = 0 THEN 'ATIVA'
WHEN NFE.CANC_NF_SAIDA = 1 THEN 'CANCELADA' 
END AS [STATUS NFE]
FROM NFE AS NFE 
LEFT JOIN OS_NF AS OS_NF ON OS_NF.COD_NF_SAIDA = NFE.COD_NF_SAIDA
INNER JOIN CLIENTES AS CLI ON CLI.COD_CLI = NFE.COD_CLI
LEFT JOIN OS ON OS.COD_OS = OS_NF.COD_OS
LEFT JOIN CONTRATO_CLIENTE AS CONT ON CONT.COD_CLI = CLI.COD_CLI AND CONT.COD_CONTRATO = OS.COD_CONTRATO
LEFT JOIN CONTRATO AS CONTRATO ON CONTRATO.COD_CONTRATO = CONT.COD_CONTRATO
INNER JOIN NATUREZA_OPERACAO AS NAT ON NAT.COD_NAT = NFE.COD_NAT
/* consultor solicitou para retirar o filtro por data de OS */
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM /*AND OS.DAT1_OS BETWEEN @INI AND @FIM*/
AND OS_NF.MODELO_NF = 'N' AND OS_NF.EMPRESA_NF_SAIDA = 'T'

UNION all 

SELECT 'TECHCD SERVIÇO' AS ENPRESA,  NFE.COD_NF_SAIDA AS CODIGO, CONVERT(NVARCHAR,NFE.DATAEMIS_NF_SAIDA,103) AS DATA_EMISSAO_NFE,  
OS_NF.COD_OS AS OS, CONVERT(NVARCHAR,OS.DATA2_OS,103) AS DATA_EMISSAO_OS, CLI.COD_CLI AS CODIGO_CLIENTE,
CLI.NOME_CLI AS NOME_CLIENTE, CASE 
WHEN CLI.PES_CLI = 'j' THEN CLI.CNPJ_CLI
ELSE CLI.CPF_CLI END CNPJ_CPF, NAT.DESC_NAT AS [NATUREZA DA OPERAÇÃO] ,CONTRATO.NUM_CONTRATO CODIGO_CONTRATO, 
NFE.TOTFRETE_NF_SAIDA AS VALOR_FRETE, NFE.TOTPROD_NF_SAIDA AS TOTAL_PRODUTO, NFE.TOTSERV_NF_SAIDA AS TOTAL_SERVICO, 
NFE.SUBST_TRIBUTARIA AS ST,NFE.VAL_ICMS AS ICMS, 
NFE.IPI_NF_SAIDA AS IPI, NFE.TOTAL_NF_SAIDA AS TOTAL_NFE , 
CASE 
WHEN NFE.CANC_NF_SAIDA = 0 THEN 'ATIVA'
WHEN NFE.CANC_NF_SAIDA = 1 THEN 'CANCELADA' 
END AS [STATUS NFE]
FROM NFE_SRV AS NFE 
LEFT JOIN OS_NF AS OS_NF ON OS_NF.COD_NF_SAIDA = NFE.COD_NF_SAIDA
INNER JOIN CLIENTES AS CLI ON CLI.COD_CLI = NFE.COD_CLI
LEFT JOIN OS ON OS.COD_OS = OS_NF.COD_OS
LEFT JOIN CONTRATO_CLIENTE AS CONT ON CONT.COD_CLI = CLI.COD_CLI AND CONT.COD_CONTRATO = OS.COD_CONTRATO
LEFT JOIN CONTRATO AS CONTRATO ON CONTRATO.COD_CONTRATO = CONT.COD_CONTRATO
INNER JOIN NATUREZA_OPERACAO AS NAT ON NAT.COD_NAT = NFE.COD_NAT
/*as notas de serviço precisam manter o filtro de data por OS, senão o relatorio traz datas OS 
antigas isso por causa que o banco não esta normalizado, e como foi criado um outra tabela pra NFS comoçando
do zero ele acabaca não entendedo, houve tempo nem prioridade para esse ajuste */
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM AND OS.DATA1_OS BETWEEN @INI AND @FIM
AND OS_NF.MODELO_NF = 'N' AND OS_NF.EMPRESA_NF_SAIDA = 'T'

UNION all 
--------------------------------------------------------------------------------------------------------- CABEÇALHO  MIDIA CENTER 
SELECT 'MIDIA CENTER' AS ENPRESA,  NFE.COD_NF_SAIDA AS CODIGO, 
CONVERT(NVARCHAR,NFE.DATAEMIS_NF_SAIDA,103) AS DATA_EMISSAO_NFE,  
OS_NF.COD_OS AS OS, CONVERT(NVARCHAR,OS.DATA2_OS,103) AS DATA_EMISSAO_OS, CLI.COD_CLI AS CODIGO_CLIENTE,
CLI.NOME_CLI AS NOME_CLIENTE, CASE 
WHEN CLI.PES_CLI = 'j' THEN CLI.CNPJ_CLI
ELSE CLI.CPF_CLI END CNPJ_CPF, NAT.DESC_NAT AS [NATUREZA DA OPERAÇÃO] ,CONTRATO.NUM_CONTRATO CODIGO_CONTRATO, 
NFE.TOTFRETE_NF_SAIDA AS VALOR_FRETE, NFE.TOTPROD_NF_SAIDA AS TOTAL_PRODUTO, NFE.TOTSERV_NF_SAIDA AS TOTAL_SERVICO, 
NFE.SUBST_TRIBUTARIA AS ST,NFE.VAL_ICMS AS ICMS, 
NFE.IPI_NF_SAIDA AS IPI, NFE.TOTAL_NF_SAIDA AS TOTAL_NFE , 
CASE 
WHEN NFE.CANC_NF_SAIDA = 0 THEN 'ATIVA'
WHEN NFE.CANC_NF_SAIDA = 1 THEN 'CANCELADA' 
END AS [STATUS NFE]
FROM NFE_MIDIA AS NFE 
LEFT JOIN OS_NF AS OS_NF ON OS_NF.COD_NF_SAIDA = NFE.COD_NF_SAIDA
INNER JOIN CLIENTES AS CLI ON CLI.COD_CLI = NFE.COD_CLI
LEFT JOIN OS ON OS.COD_OS = OS_NF.COD_OS
LEFT JOIN CONTRATO_CLIENTE AS CONT ON CONT.COD_CLI = CLI.COD_CLI AND CONT.COD_CONTRATO = OS.COD_CONTRATO
LEFT JOIN CONTRATO AS CONTRATO ON CONTRATO.COD_CONTRATO = CONT.COD_CONTRATO
INNER JOIN NATUREZA_OPERACAO AS NAT ON NAT.COD_NAT = NFE.COD_NAT
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM /* AND OS.DATA1_OS BETWEEN @INI AND @FIM */
AND OS_NF.MODELO_NF = 'N' AND OS_NF.EMPRESA_NF_SAIDA = 'M'

UNION all

SELECT 'MIDIA CENTER SERVIÇO' AS ENPRESA,  NFE.COD_NF_SAIDA AS CODIGO, 
CONVERT(NVARCHAR,NFE.DATAEMIS_NF_SAIDA,103) AS DATA_EMISSAO_NFE,  
OS_NF.COD_OS AS OS, CONVERT(NVARCHAR,OS.DATA2_OS,103) AS DATA_EMISSAO_OS, CLI.COD_CLI AS CODIGO_CLIENTE,
CLI.NOME_CLI AS NOME_CLIENTE, CASE 
WHEN CLI.PES_CLI = 'j' THEN CLI.CNPJ_CLI
ELSE CLI.CPF_CLI END CNPJ_CPF, NAT.DESC_NAT AS [NATUREZA DA OPERAÇÃO] ,CONTRATO.NUM_CONTRATO CODIGO_CONTRATO, 
NFE.TOTFRETE_NF_SAIDA AS VALOR_FRETE, NFE.TOTPROD_NF_SAIDA AS TOTAL_PRODUTO, NFE.TOTSERV_NF_SAIDA AS TOTAL_SERVICO, 
NFE.SUBST_TRIBUTARIA AS ST,NFE.VAL_ICMS AS ICMS, 
NFE.IPI_NF_SAIDA AS IPI, NFE.TOTAL_NF_SAIDA AS TOTAL_NFE , 
CASE 
WHEN NFE.CANC_NF_SAIDA = 0 THEN 'ATIVA'
WHEN NFE.CANC_NF_SAIDA = 1 THEN 'CANCELADA' 
END AS [STATUS NFE]
FROM NFE_MIDIA_SRV AS NFE 
LEFT JOIN OS_NF AS OS_NF ON OS_NF.COD_NF_SAIDA = NFE.COD_NF_SAIDA
INNER JOIN CLIENTES AS CLI ON CLI.COD_CLI = NFE.COD_CLI
LEFT JOIN OS ON OS.COD_OS = OS_NF.COD_OS
LEFT JOIN CONTRATO_CLIENTE AS CONT ON CONT.COD_CLI = CLI.COD_CLI AND CONT.COD_CONTRATO = OS.COD_CONTRATO
LEFT JOIN CONTRATO AS CONTRATO ON CONTRATO.COD_CONTRATO = CONT.COD_CONTRATO
INNER JOIN NATUREZA_OPERACAO AS NAT ON NAT.COD_NAT = NFE.COD_NAT
/*as notas de serviço precisam manter o filtro de data por OS, senão o relatorio traz datas OS 
antigas isso por causa que o banco não esta normalizado, e como foi criado um outra tabela pra NFS comoçando
do zero ele acabaca não entendedo, houve tempo nem prioridade para esse ajuste */
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM AND OS.DATA1_OS BETWEEN @INI AND @FIM
AND OS_NF.MODELO_NF = 'N' AND OS_NF.EMPRESA_NF_SAIDA = 'M'


UNION all 
------------------------------------------------------------------------------------------------------- CABEÇALHO  DATA STORE  
SELECT 'DATA STORE' AS ENPRESA,  NFE.COD_NF_SAIDA AS CODIGO, 
CONVERT(NVARCHAR,NFE.DATAEMIS_NF_SAIDA,103) AS DATA_EMISSAO_NFE,  
OS_NF.COD_OS AS OS, CONVERT(NVARCHAR,OS.DATA2_OS,103) AS DATA_EMISSAO_OS, CLI.COD_CLI AS CODIGO_CLIENTE,
CLI.NOME_CLI AS NOME_CLIENTE, CASE 
WHEN CLI.PES_CLI = 'j' THEN CLI.CNPJ_CLI
ELSE CLI.CPF_CLI END CNPJ_CPF, NAT.DESC_NAT AS [NATUREZA DA OPERAÇÃO] ,CONTRATO.NUM_CONTRATO CODIGO_CONTRATO, 
NFE.TOTFRETE_NF_SAIDA AS VALOR_FRETE, NFE.TOTPROD_NF_SAIDA AS TOTAL_PRODUTO, NFE.TOTSERV_NF_SAIDA AS TOTAL_SERVICO, 
NFE.SUBST_TRIBUTARIA AS ST,NFE.VAL_ICMS AS ICMS, 
NFE.IPI_NF_SAIDA AS IPI, NFE.TOTAL_NF_SAIDA AS TOTAL_NFE , 
CASE 
WHEN NFE.CANC_NF_SAIDA = 0 THEN 'ATIVA'
WHEN NFE.CANC_NF_SAIDA = 1 THEN 'CANCELADA' 
END AS [STATUS NFE]
FROM NFE_DATA AS NFE 
LEFT JOIN OS_NF AS OS_NF ON OS_NF.COD_NF_SAIDA = NFE.COD_NF_SAIDA
INNER JOIN CLIENTES AS CLI ON CLI.COD_CLI = NFE.COD_CLI
LEFT JOIN OS ON OS.COD_OS = OS_NF.COD_OS
LEFT JOIN CONTRATO_CLIENTE AS CONT ON CONT.COD_CLI = CLI.COD_CLI AND CONT.COD_CONTRATO = OS.COD_CONTRATO
LEFT JOIN CONTRATO AS CONTRATO ON CONTRATO.COD_CONTRATO = CONT.COD_CONTRATO
INNER JOIN NATUREZA_OPERACAO AS NAT ON NAT.COD_NAT = NFE.COD_NAT
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM /* AND OS.DATA1_OS BETWEEN @INI AND @FIM*/ 
AND OS_NF.MODELO_NF = 'N' AND OS_NF.EMPRESA_NF_SAIDA =  'D'

UNION all

SELECT 'DATA STORE SERVICO' AS ENPRESA,  NFE.COD_NF_SAIDA AS CODIGO,
 CONVERT(NVARCHAR,NFE.DATAEMIS_NF_SAIDA,103) AS DATA_EMISSAO_NFE,  
OS_NF.COD_OS AS OS, CONVERT(NVARCHAR,OS.DATA2_OS,103) AS DATA_EMISSAO_OS, CLI.COD_CLI AS CODIGO_CLIENTE,
CLI.NOME_CLI AS NOME_CLIENTE, CASE 
WHEN CLI.PES_CLI = 'j' THEN CLI.CNPJ_CLI
ELSE CLI.CPF_CLI END CNPJ_CPF, NAT.DESC_NAT AS [NATUREZA DA OPERAÇÃO] ,CONTRATO.NUM_CONTRATO CODIGO_CONTRATO, 
NFE.TOTFRETE_NF_SAIDA AS VALOR_FRETE, NFE.TOTPROD_NF_SAIDA AS TOTAL_PRODUTO, NFE.TOTSERV_NF_SAIDA AS TOTAL_SERVICO, 
NFE.SUBST_TRIBUTARIA AS ST,NFE.VAL_ICMS AS ICMS, 
NFE.IPI_NF_SAIDA AS IPI, NFE.TOTAL_NF_SAIDA AS TOTAL_NFE , 
CASE 
WHEN NFE.CANC_NF_SAIDA = 0 THEN 'ATIVA'
WHEN NFE.CANC_NF_SAIDA = 1 THEN 'CANCELADA' 
END AS [STATUS NFE]
FROM NFE_DATA_SRV AS NFE 
LEFT JOIN OS_NF AS OS_NF ON OS_NF.COD_NF_SAIDA = NFE.COD_NF_SAIDA
INNER JOIN CLIENTES AS CLI ON CLI.COD_CLI = NFE.COD_CLI
LEFT JOIN OS ON OS.COD_OS = OS_NF.COD_OS
LEFT JOIN CONTRATO_CLIENTE AS CONT ON CONT.COD_CLI = CLI.COD_CLI AND CONT.COD_CONTRATO = OS.COD_CONTRATO
LEFT JOIN CONTRATO AS CONTRATO ON CONTRATO.COD_CONTRATO = CONT.COD_CONTRATO
INNER JOIN NATUREZA_OPERACAO AS NAT ON NAT.COD_NAT = NFE.COD_NAT
/*as notas de serviço precisam manter o filtro de data por OS, senão o relatorio traz datas OS 
antigas isso por causa que o banco não esta normalizado, e como foi criado um outra tabela pra NFS comoçando
do zero ele acabaca não entendedo, houve tempo nem prioridade para esse ajuste */
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM AND OS.DATA1_OS BETWEEN @INI AND @FIM 
AND OS_NF.MODELO_NF = 'N' AND OS_NF.EMPRESA_NF_SAIDA = 'D'


order by CODIGO asc 