/**
10. Código do Produto/Serviço: código do serviço/produto da OS.
11. Descrição do Produto/Serviço: descrição do serviço/produto da OS.
12. *Quantidade: quantidade do produto/serviço vendido.
13. *Preço de Venda: valor de venda unitário do produto/serviço vendido.
14. *Valor total: valor total do produto/serviço vendido.
**/

USE TECHCD 

DECLARE @INI AS DATETIME = '2016-01-01'
DECLARE @FIM AS DATETIME = '2016-05-31'

-----------------------------------------------------------------  TECHCD 

SELECT 'TECHCD' AS ENPRESA, ITEM.COD_NF_SAIDA ,CASE 
WHEN ITEM.COD_PROD = 0 THEN ITEM.COD_SERV 
ELSE ITEM.COD_PROD END SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN SERV.DESC_SERV ELSE PROD.DESC_PROD END DESCRICAO_SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN 'SERVICO' ELSE 'PRODUTO' END TIPO_PRODUTO_SERVICO,  
ITEM.QTDE_NF_SAIDA AS QUANTIDADE, ITEM.VALOR_NF_SAIDA AS VALOR_UNITARIO,
(ITEM.QTDE_NF_SAIDA * ITEM.VALOR_NF_SAIDA) AS VALOR_TOTAL_DO_ITEM
FROM ITM_NFE_SAIDA AS ITEM 
INNER JOIN NFE AS NFE ON NFE.COD_NF_SAIDA =  ITEM.COD_NF_SAIDA
LEFT JOIN PRODUTOS AS PROD ON PROD.COD_PROD = ITEM.COD_PROD
LEFT JOIN SERVICOS AS SERV ON SERV.COD_SERV = ITEM.COD_SERV
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM

UNION ALL 

SELECT 'TECHCD SERVIÇO' AS ENPRESA, ITEM.COD_NF_SAIDA ,CASE 
WHEN ITEM.COD_PROD = 0 THEN ITEM.COD_SERV 
ELSE ITEM.COD_PROD END SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN SERV.DESC_SERV ELSE PROD.DESC_PROD END DESCRICAO_SERVICO_PRODUTO,
CASE WHEN ITEM.COD_PROD = 0 THEN 'SERVICO' ELSE 'PRODUTO' END TIPO_PRODUTO_SERVICO,  
ITEM.QTDE_NF_SAIDA AS QUANTIDADE, ITEM.VALOR_NF_SAIDA AS VALOR_UNITARIO,
(ITEM.QTDE_NF_SAIDA * ITEM.VALOR_NF_SAIDA) AS VALOR_TOTAL_DO_ITEM
FROM ITM_NFE_SAIDA_SRV AS ITEM 
INNER JOIN NFE_SRV AS NFE ON NFE.COD_NF_SAIDA =  ITEM.COD_NF_SAIDA
LEFT JOIN PRODUTOS AS PROD ON PROD.COD_PROD = ITEM.COD_PROD
LEFT JOIN SERVICOS AS SERV ON SERV.COD_SERV = ITEM.COD_SERV
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM

UNION ALL 

SELECT 'DATA STORE' AS ENPRESA, ITEM.COD_NF_SAIDA ,CASE 
WHEN ITEM.COD_PROD = 0 THEN ITEM.COD_SERV 
ELSE ITEM.COD_PROD END SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN SERV.DESC_SERV ELSE PROD.DESC_PROD END DESCRICAO_SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN 'SERVICO' ELSE 'PRODUTO' END TIPO_PRODUTO_SERVICO,  
ITEM.QTDE_NF_SAIDA AS QUANTIDADE, ITEM.VALOR_NF_SAIDA AS VALOR_UNITARIO,
(ITEM.QTDE_NF_SAIDA * ITEM.VALOR_NF_SAIDA) AS VALOR_TOTAL_DO_ITEM
FROM ITM_NFE_SAIDA_DATA AS ITEM 
INNER JOIN NFE_DATA AS NFE ON NFE.COD_NF_SAIDA =  ITEM.COD_NF_SAIDA
LEFT JOIN PRODUTOS AS PROD ON PROD.COD_PROD = ITEM.COD_PROD
LEFT JOIN SERVICOS AS SERV ON SERV.COD_SERV = ITEM.COD_SERV
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM

UNION ALL 

SELECT 'DATA STORE SERVIÇO' AS ENPRESA, ITEM.COD_NF_SAIDA ,CASE 
WHEN ITEM.COD_PROD = 0 THEN ITEM.COD_SERV 
ELSE ITEM.COD_PROD END SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN SERV.DESC_SERV ELSE PROD.DESC_PROD END DESCRICAO_SERVICO_PRODUTO,
CASE WHEN ITEM.COD_PROD = 0 THEN 'SERVICO' ELSE 'PRODUTO' END TIPO_PRODUTO_SERVICO,  
ITEM.QTDE_NF_SAIDA AS QUANTIDADE, ITEM.VALOR_NF_SAIDA AS VALOR_UNITARIO,
(ITEM.QTDE_NF_SAIDA * ITEM.VALOR_NF_SAIDA) AS VALOR_TOTAL_DO_ITEM
FROM ITM_NFE_SAIDA_DATA_SRV AS ITEM 
INNER JOIN NFE_DATA_SRV AS NFE ON NFE.COD_NF_SAIDA =  ITEM.COD_NF_SAIDA
LEFT JOIN PRODUTOS AS PROD ON PROD.COD_PROD = ITEM.COD_PROD
LEFT JOIN SERVICOS AS SERV ON SERV.COD_SERV = ITEM.COD_SERV
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM

UNION ALL 

SELECT 'MIDIA CENTER' AS ENPRESA, ITEM.COD_NF_SAIDA ,CASE 
WHEN ITEM.COD_PROD = 0 THEN ITEM.COD_SERV 
ELSE ITEM.COD_PROD END SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN SERV.DESC_SERV ELSE PROD.DESC_PROD END DESCRICAO_SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN 'SERVICO' ELSE 'PRODUTO' END TIPO_PRODUTO_SERVICO,  
ITEM.QTDE_NF_SAIDA AS QUANTIDADE, ITEM.VALOR_NF_SAIDA AS VALOR_UNITARIO,
(ITEM.QTDE_NF_SAIDA * ITEM.VALOR_NF_SAIDA) AS VALOR_TOTAL_DO_ITEM
FROM ITM_NFE_SAIDA_MIDIA AS ITEM 
INNER JOIN NFE_MIDIA AS NFE ON NFE.COD_NF_SAIDA =  ITEM.COD_NF_SAIDA
LEFT JOIN PRODUTOS AS PROD ON PROD.COD_PROD = ITEM.COD_PROD
LEFT JOIN SERVICOS AS SERV ON SERV.COD_SERV = ITEM.COD_SERV
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM

UNION ALL 

SELECT 'MIDIA CENTER SERVIÇO' AS ENPRESA, ITEM.COD_NF_SAIDA ,CASE 
WHEN ITEM.COD_PROD = 0 THEN ITEM.COD_SERV 
ELSE ITEM.COD_PROD END SERVICO_PRODUTO,  
CASE WHEN ITEM.COD_PROD = 0 THEN SERV.DESC_SERV ELSE PROD.DESC_PROD END DESCRICAO_SERVICO_PRODUTO,
CASE WHEN ITEM.COD_PROD = 0 THEN 'SERVICO' ELSE 'PRODUTO' END TIPO_PRODUTO_SERVICO,  
ITEM.QTDE_NF_SAIDA AS QUANTIDADE, ITEM.VALOR_NF_SAIDA AS VALOR_UNITARIO,
(ITEM.QTDE_NF_SAIDA * ITEM.VALOR_NF_SAIDA) AS VALOR_TOTAL_DO_ITEM
FROM ITM_NFE_SAIDA_MIDIA_SRV AS ITEM 
INNER JOIN NFE_MIDIA_SRV AS NFE ON NFE.COD_NF_SAIDA =  ITEM.COD_NF_SAIDA
LEFT JOIN PRODUTOS AS PROD ON PROD.COD_PROD = ITEM.COD_PROD
LEFT JOIN SERVICOS AS SERV ON SERV.COD_SERV = ITEM.COD_SERV
WHERE NFE.DATAEMIS_NF_SAIDA BETWEEN @INI AND @FIM

ORDER BY ITEM.COD_NF_SAIDA


