--Contas a Pagar
----NFE	FORNECEDOR	EMISSAO	VENCIMENTO	 VALOR
--- TECHCD 
use techcd

declare @fim datetime = '2016-08-01'
declare @venc datetime ='2016-08-01'

SELECT NFE.COD_NF_ENTRADA AS NFE, F.NOME_FORN AS FORNECEDOR  , 
CONVERT(NVARCHAR,NFE.DATA_EMISS,103) AS EMISSAO , 
CONVERT(NVARCHAR,ITM.VENC_PARC,103) AS VENCIMENTO, ITM.VAL_PARC AS PARCELA 
FROM nfe_entrada AS NFE  
INNER JOIN FORNECEDORES AS F ON F.COD_FORN = NFE.COD_FORN
INNER JOIN itm_nfe_entrada_PAGTO AS ITM ON ITM.COD_NF_ENTRADA =  NFE.COD_NF_ENTRADA
WHERE nfe.DATA_EMISS BETWEEN '1999-01-01' AND @fim 
ORDER BY ITM.VENC_PARC

------------------------------------------------------------------------------------------------------------- DATA STORE 
SELECT NFE.COD_NF_ENTRADA AS NFE, F.NOME_FORN AS FORNECEDOR  , 
CONVERT(NVARCHAR,NFE.DATA_EMISS,103) AS EMISSAO , 
CONVERT(NVARCHAR,ITM.VENC_PARC,103) AS VENCIMENTO, ITM.VAL_PARC AS PARCELA 
FROM nfe_ENTRADA_DATA AS NFE  
INNER JOIN FORNECEDORES AS F ON F.COD_FORN = NFE.COD_FORN
INNER JOIN ITM_NFe_ENTRADA_pagto_DATA AS ITM ON ITM.COD_NF_ENTRADA =  NFE.COD_NF_ENTRADA
WHERE nfe.DATA_EMISS BETWEEN '1999-01-01' AND @fim 
ORDER BY ITM.VENC_PARC
------------------------------------------------------------------------------------------------------------- MIDIA CENTER 
SELECT NFE.COD_NF_ENTRADA AS NFE, F.NOME_FORN AS FORNECEDOR  , 
CONVERT(NVARCHAR,NFE.DATA_EMISS,103) AS EMISSAO , 
CONVERT(NVARCHAR,ITM.VENC_PARC,103) AS VENCIMENTO, ITM.VAL_PARC AS PARCELA 
FROM nfe_ENTRADA_midia AS NFE  
INNER JOIN FORNECEDORES AS F ON F.COD_FORN = NFE.COD_FORN
INNER JOIN ITM_NFe_ENTRADA_pagto_midia AS ITM ON ITM.COD_NF_ENTRADA =  NFE.COD_NF_ENTRADA
WHERE nfe.DATA_EMISS BETWEEN '1999-01-01' AND @fim 
ORDER BY ITM.VENC_PARC

