
--Contas a Receber
--- Cod_NF_Saida	 valnf_saida_pagto 	parcnf_saida_pagto	
--- datavencnf_saida_pagto	nome_cli	 nome_func 	desc_pagto	
--- Desc_FrmPagto	Cod_OS	Qtde_OS	emissao
--and ITEM.DATAQUITNF_SAIDA_PAGTO is null 

use techcd
Declare @ini datetime = '1999-01-01'
Declare @fim datetime = '2016-07-01' 

--TECHCD NFE ======================================================================================================= techcd 
SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO], 
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NFE AS N
INNER JOIN ITM_NFE_SAIDA_PAGTO AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =  ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim  and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim



UNION ALL -- NOTAS SERVIÇO

SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO], 
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NFE_SRV AS N
INNER JOIN ITM_NFE_SAIDA_PAGTO_SRV AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =  ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim

UNION ALL -- SERVIÇO

SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO], 
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NOTAS_FISCAIS AS N
INNER JOIN ITM_NF_SAIDA_PAGTO AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =   ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim

ORDER BY NFE ASC 

--DATA STORE  -- NFE ========================================================================================================= data store
SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO ],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO], 
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NFE_DATA AS N
INNER JOIN ITM_NFE_SAIDA_PAGTO_DATA AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =   ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim

UNION ALL -- NOTAS ANTIGAS 

SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO ],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO], 
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NOTAS_FISCAIS_DATA AS N
INNER JOIN ITM_NF_SAIDA_PAGTO_DATA AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =   ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim

UNION ALL -- SERVIÇOS

SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO ],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO], 
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NFE_DATA_SRV AS N
INNER JOIN ITM_NFE_SAIDA_PAGTO_DATA_SRV AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =   ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim

ORDER BY NFE ASC 

--MIDIA CENTER NFE =================================================================================================================== midias center 
SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO ],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO],
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NFE_MIDIA AS N
INNER JOIN ITM_NFE_SAIDA_PAGTO_MIDIA AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER  JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =  ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim

UNION ALL --- NOTAS ANTIGAS 

SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO ],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO], 
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NOTAS_FISCAIS_MIDIA AS N
INNER JOIN ITM_NF_SAIDA_PAGTO_MIDIA AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER  JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =   ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim

UNION --- NFE SERVIÇO

SELECT N.COD_NF_SAIDA AS NFE,  C.NOME_CLI AS CLIENTE , ITEM.PARCNF_SAIDA_PAGTO AS PARCELA, 
ITEM.VALNF_SAIDA_PAGTO AS [VALOR SAIDA] , TP.DESC_PAGTO AS [TIPO DE PAGAMENTO ],
FP.DESC_FRMPAGTO AS [FORMA DE PAGAMENTO], 
CONVERT(NVARCHAR,ITEM.DATAVENCNF_SAIDA_PAGTO,103) AS [DATA VENCIMENTO],
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA EMISSAO],
ISNULL(CONVERT(NVARCHAR,ITEM.DATAQUITNF_SAIDA_PAGTO,103),'EM ABERTO') AS [QUITADA EM]
FROM NFE_MIDIA_SRV AS N
INNER JOIN ITM_NFE_SAIDA_PAGTO_MIDIA_SRV AS ITEM ON ITEM.COD_NF_SAIDA =  N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI
INNER JOIN FORMA_PAGTO AS FP ON FP.COD_FRMPAGTO = ITEM.COD_FRMPAGTO
INNER  JOIN TIPO_PAGTO AS TP ON TP.COD_PAGTO =   ITEM.COD_PAGTO
WHERE N.DATAEMIS_NF_SAIDA BETWEEN @ini AND @fim and N.CANC_NF_SAIDA=0
--AND ITEM.QUEMQUITNF_SAIDA_PAGTO IS NULL
--OR ITEM.DATAQUITNF_SAIDA_PAGTO < @fim

ORDER BY NFE ASC 
