
SELECT DISTINCT C.COD_CLI AS [ID CLIENTE], C.NOME_CLI AS [CLIENTE], CONVERT(DATE,C.DATAINCL_CLI,103)[CADASTRO], 
CASE WHEN C.PES_CLI = 'J' THEN 'JURIDICO' ELSE 'FISICO' END [TIPO CLIENTE], C.EST_CLI [ESTADO], 
CASE WHEN ITEM.COD_PROD > 0 THEN 'PRODUTO' ELSE 'SERVIÇO' END [TIPO DE AQUISIÇÃO],
CASE WHEN ITEM.COD_PROD > 0 THEN ITEM.COD_PROD
WHEN ITEM.COD_SERV > 0 THEN ITEM.COD_SERV  
END AS [ID PRODUTO / SERVIÇO],
CASE WHEN ITEM.COD_PROD > 0 THEN PROD.DESC_PROD
WHEN ITEM.COD_SERV > 0 THEN SERV.DESC_SERV
END AS [PRODUTO / SERVIÇO], 
SUM(ITEM.QTDE_OS) AS [QUANTIDADE],
CONVERT(date,MAX(OS.DATA1_OS),103) AS [ULTIMA COMPRA] , MAX(ITEM.VALOR_OS) AS [ULTIMO PREÇO]
FROM CLIENTES C
INNER JOIN OS ON OS.COD_CLI = C.COD_CLI
INNER JOIN ITM_OS AS ITEM ON ITEM.COD_OS =  OS.COD_OS
LEFT JOIN PRODUTOS AS PROD ON PROD.COD_PROD = ITEM.COD_PROD
LEFT JOIN SERVICOS AS SERV ON SERV.COD_SERV = ITEM.COD_SERV
GROUP BY C.COD_CLI, C.NOME_CLI, C.DATAINCL_CLI, C.PES_CLI, ITEM.COD_PROD, C.EST_CLI, PROD.DESC_PROD, 
ITEM.COD_SERV, SERV.DESC_SERV
ORDER BY [ULTIMA COMPRA] DESC 


SELECT CLIENTES.NOME_CLI, C.* FROM CLIENTES 
INNER JOIN CONTATOS_CLI AS C ON C.COD_CLI =  CLIENTES.COD_CLI


