
INSERT INTO SUB_TRIBUTARIA SELECT * FROM  OPENROWSET('Microsoft.ACE.OLEDB.12.0',
    'Excel 12.0 Xml;HDR=YES;Database=C:\backup_sql\tabela NCM MVA-st.xlsx',
    'SELECT  NCM,Estado,MVA_AJUSTADO,MVA_IMP,MVA_ORIGINAL,ICMS_INTRA,
    	ICMS_INTRA_2,ICMS_INTER,ICMS_IMP,PROTOCOLO FROM [techcd$]') 
SELECT * FROM SUB_TRIBUTARIA  
