/*RELATORIO TECHCD GARANTIA */
SELECT N.COD_NF_SAIDA AS NFE , I.COD_SERV  , UPPER(S.DESC_SERV) AS DESCRICAO , 
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA DE EMISSAO], 
C.COD_CLI , UPPER(C.NOME_CLI) AS CLIENTE , C.CNPJ_CLI , UPPER(C.EST_CLI)AS ESTADO , UPPER(C.CID_CLI) AS CIDADE 
FROM NFE AS N
INNER JOIN ITM_NFE_SAIDA AS I ON I.COD_NF_SAIDA = N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI 
INNER JOIN SERVICOS AS S ON S.COD_SERV = I.COD_SERV
WHERE I.COD_SERV IN(SELECT COD_SERV FROM SERVICOS WHERE COD_SERV = 31005)
GROUP BY N.COD_NF_SAIDA  , I.COD_SERV  , UPPER(S.DESC_SERV) , N.DATAEMIS_NF_SAIDA , 
C.COD_CLI , C.NOME_CLI , C.CNPJ_CLI , C.EST_CLI , C.CID_CLI
ORDER BY N.DATAEMIS_NF_SAIDA ASC 

/*RELATORIO MIDIA GARANTIA */

SELECT N.COD_NF_SAIDA AS NFE , I.COD_SERV  , UPPER(S.DESC_SERV) AS DESCRICAO , 
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA DE EMISSAO], 
C.COD_CLI , UPPER(C.NOME_CLI) AS CLIENTE , C.CNPJ_CLI , UPPER(C.EST_CLI)AS ESTADO , UPPER(C.CID_CLI) AS CIDADE 
FROM NFE_MIDIA AS N
INNER JOIN ITM_NFE_SAIDA_MIDIA AS I ON I.COD_NF_SAIDA = N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI 
INNER JOIN SERVICOS AS S ON S.COD_SERV = I.COD_SERV
WHERE I.COD_SERV IN(SELECT COD_SERV FROM SERVICOS WHERE COD_SERV = 31005)
GROUP BY N.COD_NF_SAIDA  , I.COD_SERV  , UPPER(S.DESC_SERV) , N.DATAEMIS_NF_SAIDA , 
C.COD_CLI , C.NOME_CLI , C.CNPJ_CLI , C.EST_CLI , C.CID_CLI
ORDER BY N.DATAEMIS_NF_SAIDA ASC 


/*RELATORIO DATA GARANTIA */

SELECT N.COD_NF_SAIDA AS NFE , I.COD_SERV  , UPPER(S.DESC_SERV) AS DESCRICAO , 
CONVERT(NVARCHAR,N.DATAEMIS_NF_SAIDA,103) AS [DATA DE EMISSAO], 
C.COD_CLI , UPPER(C.NOME_CLI) AS CLIENTE , C.CNPJ_CLI , UPPER(C.EST_CLI)AS ESTADO , UPPER(C.CID_CLI) AS CIDADE 
FROM NFE_DATA AS N
INNER JOIN ITM_NFE_SAIDA_MIDIA AS I ON I.COD_NF_SAIDA = N.COD_NF_SAIDA
INNER JOIN CLIENTES AS C ON C.COD_CLI =  N.COD_CLI 
INNER JOIN SERVICOS AS S ON S.COD_SERV = I.COD_SERV
WHERE I.COD_SERV IN(SELECT COD_SERV FROM SERVICOS WHERE COD_SERV = 31005)
GROUP BY N.COD_NF_SAIDA  , I.COD_SERV  , UPPER(S.DESC_SERV) , N.DATAEMIS_NF_SAIDA , 
C.COD_CLI , C.NOME_CLI , C.CNPJ_CLI , C.EST_CLI , C.CID_CLI
ORDER BY N.DATAEMIS_NF_SAIDA ASC 